---
- name: idle-checker
  hosts: all
  sources:
    - ansible.eda.tick:
        timeout: 900          # 15 minutes
  rules:
    - name: Reboot when idle
      condition: fact.pending_reboot

      actions:
        - run_job_template:
            name: Idle‑Probe
            organization: Default
            job_args:
              extra_vars:
                node: "{{ fact.node }}"
          register: result

        - if:
            condition: result.changed
            actions:
              - run_job_template:
                  name: GPU Remediation Workflow
                  organization: Default
                  job_args:
                    extra_vars:
                      node: "{{ fact.node }}"
              - retract_fact:
                  fact:
                    pending_reboot: true
